name: Wiki Update

# Run when contents of the wiki folder are changed
on:
  push:
    paths:
      - 'wiki/**'
    branches:
      - development

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Publish wiki folder to repository wiki
        uses: FH-Inway/github-wiki-publish-action@rsync
        with:
          path: "/github/workspace/wiki/ /github/workspace/docs/"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
